FROM centos:centos8

ARG MIRROR_TYPE=basic

COPY resources/TencentKona-11.0.16.b2-jdk_linux-x86_64.tar.gz /root/TencentKona-11.0.16.b2-jdk_linux-x86_64.tar.gz
COPY resources/apache-maven-3.8.6-bin.tar.gz /root/apache-maven-3.8.6-bin.tar.gz
COPY tencent_kona11_maven3/${MIRROR_TYPE}_settings.xml /root/.m2/settings.xml

RUN tar -zxvf /root/TencentKona-11.0.16.b2-jdk_linux-x86_64.tar.gz -C /opt \
    && mv /opt/TencentKona-11.0.16.b2 /opt/tencent_kona11 \
    && rm -f /root/TencentKona-11.0.16.b2-jdk_linux-x86_64.tar.gz \
    && tar -zxvf /root/apache-maven-3.8.6-bin.tar.gz -C /opt \
    && mv /opt/apache-maven-3.8.6 /opt/maven \
    && rm -f /root/apache-maven-3.8.6-bin.tar.gz

ENV JAVA_HOME=/opt/tencent_kona11 \
    MAVEN_HOME=/opt/maven \
    PATH=/opt/tencent_kona11/bin:/opt/maven/bin:$PATH
   